[project]
name = "wfomc"
version = "0.1.0"
description = "A exact model counter for two-variables first-order logic"
readme = "README.md"
authors = [
    { name = "lucienwang1009", email = "lucienwang1009@gmail.com" }
]
requires-python = ">=3.11"
dependencies = [
    "lark>=1.2.2",
    "networkx>=3.2.1",
    "numpy>=2.0.2",
    "pynauty==2.8.6",
    "pysdd>=1.0.0",
    "python-flint>=0.8.0",
    "python-sat>=1.9.dev5",
]

[project.scripts]
wfomc = "wfomc.cli:main"
wfomc-install-ganak = "scripts.tools.install_ganak:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/wfomc"]
force-include = { "scripts/__init__.py" = "scripts/__init__.py", "scripts/tools" = "scripts/tools" }

[dependency-groups]
dev = [
    "ipython>=9.6.0",
    "matplotlib>=3.10.9",
    "pytest>=8.4.1",
    "tabulate>=0.9.0",
    "psutil>=7.1.2",
]

[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = ["test_*.py"]
